# Generated by Django 6.0.5 on 2026-05-17 18:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('units', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('timestamp', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='billing.apikey')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='billing.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'timestamp'], name='billing_usa_custome_79a44a_idx'), models.Index(fields=['api_key', 'timestamp'], name='billing_usa_api_key_176c2a_idx')],
            },
        ),
    ]
