# Generated by Django 6.0.5 on 2026-05-17 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_usageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_windows', to='billing.apikey')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_windows', to='billing.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'window_start'], name='billing_usa_custome_a0ffa5_idx'), models.Index(fields=['api_key', 'window_start'], name='billing_usa_api_key_865770_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'api_key', 'window_start'), name='unique_usage_window_customer_api_key_hour')],
            },
        ),
    ]
