# Generated by Django 6.0.5 on 2026-05-17 19:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_priceplan_invoice_invoicelineitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('object_type', models.CharField(max_length=255)),
                ('object_id', models.CharField(max_length=255)),
                ('before_json', models.JSONField(default=dict)),
                ('after_json', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
            },
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='overridden_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.TextField()),
                ('created_by', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='billing.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='billing.invoice')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'created_at'], name='billing_cre_custome_ca1836_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'idempotency_key'), name='unique_credit_customer_idempotency_key')],
            },
        ),
    ]
